language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - master

os: linux

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

stages:
  - composer validate
  - check coding style
  - static code analysis
  - test
  - test with coverage
  - infection

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update

install: travis_retry composer update --optimize-autoloader --prefer-dist --prefer-stable --no-progress --no-interaction -vv $COMPOSER_FLAGS

script: vendor/bin/phpunit -c phpunit.xml.dist --no-coverage --colors --verbose

jobs:
  allow_failures:
    - php: master
    - php: nightly
  include:
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"

    - stage: test with coverage
      php: 7.2
      env: DEPS="NORMAL"
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - travis_retry composer self-update
      script: vendor/bin/phpunit -c phpunit.xml.dist --colors --verbose --exclude-group compare --coverage-text --coverage-clover=coverage.clover
      after_success:
        - bash <(curl -s https://codecov.io/bash) -f coverage.clover -F phpunit

    - stage: composer validate
      php: 7.2
      env: COMPOSER_FLAGS=""
      script:
        - composer validate
        - composer normalize --dry-run

    - stage: check coding style
      php: 7.2
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpcs -snp --standard=./ruleset.xml src tests

    - stage: static code analysis
      php: 7.2
      env: COMPOSER_FLAGS=""
      script: vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=768M --no-progress

    - stage: infection
      php: 7.2
      env: COMPOSER_FLAGS=""
      before_install:
        - echo 'opcache.enable=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'opcache.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
        - composer self-update
      script: vendor/bin/infection --min-covered-msi=39 --min-msi=22

notifications:
  secure: "Q8xCtM0IMQyjQuPJOPFCcFvBUlD7zwg6E5vEFfsaFQj+9bJ83Xo3loURsizTBf+WpRruDxmu3tlg0GNk5yDt92POOCOISzyWPBDmHiy2MVDfINEwyNsJpzdlw1UnChoTjSwRS3goPivfQDkOsbSrszLE93iE9PIIUw5BV4CAoho="
